# Generated by Django 5.2.8 on 2026-01-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDB',
            fields=[
                ('Customer_Name', models.CharField(max_length=12)),
                ('Order_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Mobile_No', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Ratings', models.FloatField()),
                ('Pickup_Time', models.TimeField()),
                ('Order_delivered_time', models.TimeField()),
            ],
        ),
    ]
